### ISSUE TITLE
Error: Team Request Deleted Error {"type":"gql_error","error":"can't get DB"}

### ISSUE THREAD

**Issue by hyperxpro** [jerbob92/hoppscotch-backend#10]
How I got here:

I created a team, invited a member, member joined, and everything worked fine. The member could see the collection and work.
Now I removed the member from my Team and I kept my eyes on the Network tab. There were lots of "canceled" `/graphql` requests flooded.

I refreshed the tab and the member disappeared from the team. To cross-check, I checked the invited member and indeed permissions were revoked as expected.

But when I tried to load the main tab, Hoppscotch loaded but after 3 seconds of the page loaded, I got a black screen with the error: `Error: Team Request Deleted Error {"type":"gql_error","error":"can't get DB"}`.

To fix this, I cleared the cookies of my main tab and sign-in again and things worked fine as expected as nothing happened.

Is there some backend problem with Teams Member Management in the backend?

**Comment by jerbob92** [comment]
Did you see any other errors in the logs? `can't get DB` is quite a low-level error, which should never happen.
Sounds a bit like the frontend went into some weird loop causing issues on the backend.
Do you have any steps to reproduce it?

**Comment by hyperxpro** [comment]
This was my sequence:

1. Create a Team
2. Invite the User
3. User Accepted And Join
4. Remove the user from the Team

-- > Here we go. [LOOP]

But cleaning cookies and logging back in made things normal and the user was removed from the team.

**Comment by jerbob92** [comment]
Will try to reproduce, thanks!

**Comment by jerbob92** [comment]
I sadly could not reproduce it. If you follow those steps again, does it still happen?
I used two different users in two different browsers.

**Comment by hyperxpro** [comment]
Indeed, not happening now. It might be a one-time mishap.

If it happens now, I'll report back on this issue. Let's close this for now.

**Comment by hyperxpro** [comment]
Btw, Can you help with the front end a little bit?

I am using the vanilla frontend Docker Compose file and it looks like 600+ resources each time I open it.

![Screenshot (43)](https://user-images.githubusercontent.com/24762260/217329021-1adc0834-abd4-4939-aff2-087289d16443.png)
