### ISSUE TITLE
In users table, email missing

### ISSUE THREAD

**Issue by iamdap91** [jerbob92/hoppscotch-backend#11]
<img width="794" alt="image" src="https://user-images.githubusercontent.com/45986023/219073040-0d77f04b-36ba-4848-b4d8-29ef961ea824.png">

<img width="830" alt="image" src="https://user-images.githubusercontent.com/45986023/219073943-b43d6447-d341-48c2-8b0b-429ab5a4ce8d.png">

if email is not verified in "hoppscotch profile", "email" field in the "users" table is missing.

However, even if email verification is performed, the value of the "users" table is not updated.

After email authentication, the user must be deleted and logged in again to enter the email field.

is there any options to update "users" table?  or some other solution for this?

**Comment by jerbob92** [comment]
Can you check if it has been fixed in v0.1.7?
I added logic that will update the email address in the `users` table when it updates in Firebase.

**Comment by iamdap91** [comment]
> Can you check if it has been fixed in v0.1.7? I added logic that will update the email address in the `users` table when it updates in Firebase.

Thank you. It works so good 👍👍👍👍👍👍
