### ISSUE TITLE
Error wss

### ISSUE THREAD

**Issue by bayunvnt** [jerbob92/hoppscotch-backend#2]
hello, i have problem while deploying backend with docker, i got error on websocker service
the error was :
**failed: WebSocket is closed before the connection is established.**

i using nginx as web server, can you help me to solve this issue?

thank you

**Comment by jerbob92** [comment]
Hi @bayunvnt,
To support WS with nginx reverse proxy you will need extra config:
https://www.nginx.com/blog/websocket-nginx/ http://nginx.org/en/docs/http/websocket.html

The important part is this in the nginx config:

```
        location / {
            proxy_pass http://websocket;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $host;
        }
```

That's why I made a `/graphql` route and a `/graphql/ws` route, so you can add the special WS config on the `/graphql/ws` route.

**Comment by bayunvnt** [comment]
Should i create my own websocket service? or I will be appreciate it if you can show me the full code of nginx, currently i use nginx on host and proxy pass to docker container

**Comment by jerbob92** [comment]
You can do it with nginx, it just needs some extra config. Can you show me your current config? I'll update it with the required changes.

**Comment by bayunvnt** [comment]
Here is my nginx config

location / {
                client_max_body_size 50M;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_read_timeout 600s;
                proxy_http_version 1.1;
                proxy_pass http://XXX.XXX.XXX:8989;
        }

**Comment by jerbob92** [comment]
I think it should be something like this:

```
location / {
	client_max_body_size 50M;
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_read_timeout 600s;
	proxy_pass http://XXX.XXX.XXX:8989;
}

location /graphql/ws {
	client_max_body_size 50M;
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection "Upgrade";
	proxy_read_timeout 600s;
	proxy_http_version 1.1;
	proxy_pass http://XXX.XXX.XXX:8989;
}
```

Then be sure to use /graphql for the normal API endpoint and /graphql/ws for the websockets endpoint in the frontend config.
