### ISSUE TITLE
Need to run over https...

### ISSUE THREAD

**Issue by CeloGomesBR** [jerbob92/hoppscotch-backend#6]
Hi,
Thanks a lot for your script!  Awesome work!

We installed your version and it is working like a charm.  But frontend is running on https and need to call the backend api on https too.  We are running your backend api in other port because apache is working on production server. 

Could you told us how to enable https in backend?

Thanks again!

**Comment by jerbob92** [comment]
Hey! I generally run everything through a reverse proxy that terminates the SSL to the actual backend, so I never implement SSL in my projects. But it's a legit request so I just added support for it. There is a now an SSL section in the config file where you can enable SSL and configure the path to the certificate & key.

**Comment by CeloGomesBR** [comment]
Wow!!! Fast and good!!! Thank you!  I will try it.
